#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/supperpj
#    username: root
#    password: 233235
#mybatis-plus:
#  config-location: classpath*:/mapper/**Mapper.xml
#在application.properties/或者application.yml文件中没有添加数据库配置信息.

server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://116.63.133.52:3306/ktzq-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  config-location: classpath:mapping/*.xml
  type-aliases-package: com.fzt.ktzq.dao




